#ifndef __TicTacToeMainFrame__
#define __TicTacToeMainFrame__

/**
@file
Subclass of MainFrame, which is generated by wxFormBuilder.
*/

#include "TicTacToe.h"

/** Implementing MainFrame */
class TicTacToeMainFrame : public MainFrame
{
protected:
	// Handlers for MainFrame events.
	void OnAbout( wxCommandEvent& event );
	
public:
	/** Constructor */
	TicTacToeMainFrame( wxWindow* parent );
};

#endif // __TicTacToeMainFrame__
